urdf_path: "./flying_hand_with_rotor.urdf"

camera:
  wrist_name: "wrist_camera"
  wrist_link: "mid_camera_link"

materials:
  black_color: [0.101960784313725, 0.101960784313725, 0.101960784313725, 1.0]
  silver_color: [0.8, 0.8, 0.8, 1.0]
  black_link_names:
  - "imu_odom_link"
  - "camera_link"
  - "mid_camera_link"
  - "left_up_link"
  - "left_down_link"
  - "right_down_link"
  - "right_up_link"
  - "left_tof_link"
  - "right_tof_link"
  silver_link_names:
  - "left_slide_link"
  - "down_slide_link"
  - "right_slide_link"

static_camera_list:
- name: head_camera
  position:
  - -2.25
  - 0.0
  - 1.50
  forward:
  - 1
  - 0
  - 0
  left:
  - 0
  - 1
  - 0
